### ISSUE TITLE
Font texture asset atlas

### ISSUE THREAD

**Issue by WolfieWerewolf** [Empty2k12/WebGL2SDFText#1]
Hi... great project, thanks for sharing.  I just have one question if you don't mind.  How do you generate the font .png to match the json converted from the .fnt?

Thanks
/W

**Comment by WolfieWerewolf** [comment]
Never mind.. Angelcode font... I understand now.. thanks!

**Comment by Empty2k12** [comment]
Hello @WolfieWerewolf! I think I used [Hiero](https://libgdx.badlogicgames.com/tools.html). You might want to experiment with padding and distance field values. Here is a video by ThinMatrix that explains the principle of SDF font rendering and the best configurations in Hiero: https://www.youtube.com/watch?v=d8cfgcJR9Tk
